// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	cluster.proto

It has these top-level messages:
	Node
	ClusterJoinReq
	ClusterJoinResp
	ClusterAddReq
	ClusterAddResp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto1.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ClusterJoinReq struct {
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *ClusterJoinReq) Reset()                    { *m = ClusterJoinReq{} }
func (m *ClusterJoinReq) String() string            { return proto1.CompactTextString(m) }
func (*ClusterJoinReq) ProtoMessage()               {}
func (*ClusterJoinReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClusterJoinReq) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ClusterJoinResp struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *ClusterJoinResp) Reset()                    { *m = ClusterJoinResp{} }
func (m *ClusterJoinResp) String() string            { return proto1.CompactTextString(m) }
func (*ClusterJoinResp) ProtoMessage()               {}
func (*ClusterJoinResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClusterJoinResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type ClusterAddReq struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ClusterAddReq) Reset()                    { *m = ClusterAddReq{} }
func (m *ClusterAddReq) String() string            { return proto1.CompactTextString(m) }
func (*ClusterAddReq) ProtoMessage()               {}
func (*ClusterAddReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClusterAddReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ClusterAddReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ClusterAddResp struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *ClusterAddResp) Reset()                    { *m = ClusterAddResp{} }
func (m *ClusterAddResp) String() string            { return proto1.CompactTextString(m) }
func (*ClusterAddResp) ProtoMessage()               {}
func (*ClusterAddResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClusterAddResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto1.RegisterType((*Node)(nil), "proto.Node")
	proto1.RegisterType((*ClusterJoinReq)(nil), "proto.ClusterJoinReq")
	proto1.RegisterType((*ClusterJoinResp)(nil), "proto.ClusterJoinResp")
	proto1.RegisterType((*ClusterAddReq)(nil), "proto.ClusterAddReq")
	proto1.RegisterType((*ClusterAddResp)(nil), "proto.ClusterAddResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cluster service

type ClusterClient interface {
	Join(ctx context.Context, in *ClusterJoinReq, opts ...grpc.CallOption) (*ClusterJoinResp, error)
	Add(ctx context.Context, in *ClusterAddReq, opts ...grpc.CallOption) (*ClusterAddResp, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Join(ctx context.Context, in *ClusterJoinReq, opts ...grpc.CallOption) (*ClusterJoinResp, error) {
	out := new(ClusterJoinResp)
	err := grpc.Invoke(ctx, "/proto.Cluster/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Add(ctx context.Context, in *ClusterAddReq, opts ...grpc.CallOption) (*ClusterAddResp, error) {
	out := new(ClusterAddResp)
	err := grpc.Invoke(ctx, "/proto.Cluster/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cluster service

type ClusterServer interface {
	Join(context.Context, *ClusterJoinReq) (*ClusterJoinResp, error)
	Add(context.Context, *ClusterAddReq) (*ClusterAddResp, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterJoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Cluster/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Join(ctx, req.(*ClusterJoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Cluster/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Add(ctx, req.(*ClusterAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Cluster_Join_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Cluster_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

func init() { proto1.RegisterFile("cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xd9, 0x6e, 0xea, 0xe2, 0x2c, 0x5b, 0x65, 0x68, 0xa5, 0xf4, 0xa2, 0x04, 0x05, 0x4f,
	0x45, 0x2b, 0xe2, 0xb9, 0x78, 0xf3, 0xe0, 0x21, 0xdf, 0xa0, 0x76, 0x72, 0x28, 0x96, 0x26, 0x36,
	0xad, 0xe0, 0xb7, 0x97, 0xfc, 0xe9, 0x42, 0xa1, 0xa7, 0xcc, 0xbc, 0x99, 0xf7, 0xf2, 0x1b, 0x38,
	0xb5, 0xfd, 0x6c, 0x26, 0x39, 0x96, 0x7a, 0x54, 0x93, 0xc2, 0xd8, 0x3d, 0xfc, 0x09, 0xd8, 0xa7,
	0x22, 0x89, 0x09, 0x44, 0x1d, 0xe5, 0xbb, 0xbb, 0xdd, 0xe3, 0xa5, 0x88, 0x3a, 0xc2, 0x1c, 0x0e,
	0x0d, 0xd1, 0x28, 0x8d, 0xc9, 0x23, 0x27, 0x2e, 0x2d, 0x7f, 0x86, 0xe4, 0xdd, 0x27, 0x7d, 0xa8,
	0x6e, 0x10, 0xf2, 0x07, 0x6f, 0x81, 0x0d, 0x8a, 0xa4, 0x73, 0x1f, 0xab, 0xa3, 0xff, 0xa0, 0xb4,
	0xb1, 0xc2, 0x0d, 0xf8, 0x03, 0x5c, 0xad, 0x2c, 0x46, 0x23, 0x02, 0x6b, 0x17, 0x4f, 0x2c, 0x5c,
	0xcd, 0xdf, 0xe0, 0x14, 0xd6, 0x6a, 0x22, 0x1b, 0x7c, 0x0d, 0xfb, 0x6f, 0xf9, 0x17, 0xa8, 0x6c,
	0x89, 0x29, 0xc4, 0xbf, 0x4d, 0x3f, 0xcb, 0x00, 0xe5, 0x1b, 0x7e, 0x7f, 0x46, 0x72, 0xc6, 0xed,
	0xf8, 0x6a, 0x82, 0x43, 0xd8, 0xc2, 0x57, 0x60, 0x96, 0x04, 0xb3, 0xc0, 0xba, 0x3e, 0xa8, 0xb8,
	0xd9, 0x92, 0x8d, 0xc6, 0x0a, 0xf6, 0x35, 0x11, 0xa6, 0xeb, 0xb1, 0x87, 0x2d, 0xb2, 0x0d, 0xd5,
	0xe8, 0xaf, 0x0b, 0xa7, 0xbe, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x06, 0xe5, 0xd8, 0x3f, 0x7f,
	0x01, 0x00, 0x00,
}
