// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	common.proto
	meta.proto

It has these top-level messages:
	Str
	I64
	Data
	NodeInfo
	DatabaseInfo
	RetentionPolicySpec
	RetentionPolicyInfo
	ShardGroupInfo
	ShardInfo
	SubscriptionInfo
	ShardOwner
	ContinuousQueryInfo
	UserInfo
	UserPrivilege
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Str struct {
	Val string `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
}

func (m *Str) Reset()                    { *m = Str{} }
func (m *Str) String() string            { return proto1.CompactTextString(m) }
func (*Str) ProtoMessage()               {}
func (*Str) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Str) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type I64 struct {
	Val int64 `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
}

func (m *I64) Reset()                    { *m = I64{} }
func (m *I64) String() string            { return proto1.CompactTextString(m) }
func (*I64) ProtoMessage()               {}
func (*I64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *I64) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto1.RegisterType((*Str)(nil), "proto.Str")
	proto1.RegisterType((*I64)(nil), "proto.I64")
}

func init() { proto1.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xe2, 0x5c, 0xcc,
	0xc1, 0x25, 0x45, 0x42, 0x02, 0x5c, 0xcc, 0x65, 0x89, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x20, 0x26, 0x48, 0xc2, 0xd3, 0xcc, 0x04, 0x26, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x0c, 0x96,
	0x48, 0x62, 0x03, 0x6b, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x83, 0x8f, 0x4b, 0x4f,
	0x00, 0x00, 0x00,
}
