// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	cmd.proto

It has these top-level messages:
	OptionalInt64
	OptionalString
	RetentionPolicySpec
	RetentionPolicyUpdate
	UserInfo
	MetaAcquireLeaseCmd
	MetaCreateContinuousQueryCmd
	MetaDropContinuousQueryCmd
	MetaDatabaseCmd
	MetaCreateDatabaseCmd
	MetaCreateDatabaseWithRetentionPolicyCmd
	MetaDropDatabaseCmd
	MetaCreateRetentionPolicyCmd
	MetaRetentionPolicyCmd
	MetaDropRetentionPolicyCmd
	MetaUpdateRetentionPolicyCmd
	MetaCreateSubscriptionCmd
	MetaDropSubscriptionCmd
	MetaUserCmd
	MetaCreateUserCmd
	MetaDropUserCmd
	MetaUpdateUserCmd
	MetaSetAdminPrivilegeCmd
	MetaSetPrivilegeCmd
	MetaUserPrivilegesCmd
	MetaUserPrivilegeCmd
	MetaAuthenticateCmd
	MetaShardGroupsByTimeRangeCmd
	MetaDropShardCmd
	MetaCreateShardGroupCmd
	MetaDeleteShardGroupCmd
	MetaPrecreateShardGroupsCmd
	DataCreateShardCmd
	DataWriteToShardCmd
	DataDeleteShardCmd
	DataShardGroupCmd
	DataDeleteDatabaseCmd
	DataDeleteRetentionPolicyCmd
	DataDeleteMeasurementCmd
	DataMeasurementNamesCmd
	DataMeasurementsCardinalityCmd
	DataDeleteSeriesCmd
	DataSeriesCardinalityCmd
	DataTagKeysCmd
	DataTagValuesCmd
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OptionalInt64 struct {
	Val int64 `protobuf:"varint,1,opt,name=val" json:"val,omitempty"`
}

func (m *OptionalInt64) Reset()                    { *m = OptionalInt64{} }
func (m *OptionalInt64) String() string            { return proto.CompactTextString(m) }
func (*OptionalInt64) ProtoMessage()               {}
func (*OptionalInt64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OptionalInt64) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

type OptionalString struct {
	Val string `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
}

func (m *OptionalString) Reset()                    { *m = OptionalString{} }
func (m *OptionalString) String() string            { return proto.CompactTextString(m) }
func (*OptionalString) ProtoMessage()               {}
func (*OptionalString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OptionalString) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type RetentionPolicySpec struct {
	Name               string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReplicaN           *OptionalInt64 `protobuf:"bytes,2,opt,name=replicaN" json:"replicaN,omitempty"`
	Duration           *OptionalInt64 `protobuf:"bytes,3,opt,name=duration" json:"duration,omitempty"`
	ShardGroupDuration int64          `protobuf:"varint,4,opt,name=ShardGroupDuration" json:"ShardGroupDuration,omitempty"`
}

func (m *RetentionPolicySpec) Reset()                    { *m = RetentionPolicySpec{} }
func (m *RetentionPolicySpec) String() string            { return proto.CompactTextString(m) }
func (*RetentionPolicySpec) ProtoMessage()               {}
func (*RetentionPolicySpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RetentionPolicySpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RetentionPolicySpec) GetReplicaN() *OptionalInt64 {
	if m != nil {
		return m.ReplicaN
	}
	return nil
}

func (m *RetentionPolicySpec) GetDuration() *OptionalInt64 {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *RetentionPolicySpec) GetShardGroupDuration() int64 {
	if m != nil {
		return m.ShardGroupDuration
	}
	return 0
}

type RetentionPolicyUpdate struct {
	Name               *OptionalString `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReplicaN           *OptionalInt64  `protobuf:"bytes,2,opt,name=replicaN" json:"replicaN,omitempty"`
	Duration           *OptionalInt64  `protobuf:"bytes,3,opt,name=duration" json:"duration,omitempty"`
	ShardGroupDuration *OptionalInt64  `protobuf:"bytes,4,opt,name=ShardGroupDuration" json:"ShardGroupDuration,omitempty"`
}

func (m *RetentionPolicyUpdate) Reset()                    { *m = RetentionPolicyUpdate{} }
func (m *RetentionPolicyUpdate) String() string            { return proto.CompactTextString(m) }
func (*RetentionPolicyUpdate) ProtoMessage()               {}
func (*RetentionPolicyUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RetentionPolicyUpdate) GetName() *OptionalString {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RetentionPolicyUpdate) GetReplicaN() *OptionalInt64 {
	if m != nil {
		return m.ReplicaN
	}
	return nil
}

func (m *RetentionPolicyUpdate) GetDuration() *OptionalInt64 {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *RetentionPolicyUpdate) GetShardGroupDuration() *OptionalInt64 {
	if m != nil {
		return m.ShardGroupDuration
	}
	return nil
}

type UserInfo struct {
	Name       string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hash       string           `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Admin      bool             `protobuf:"varint,3,opt,name=admin" json:"admin,omitempty"`
	Privileges map[string]int64 `protobuf:"bytes,4,rep,name=privileges" json:"privileges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *UserInfo) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *UserInfo) GetPrivileges() map[string]int64 {
	if m != nil {
		return m.Privileges
	}
	return nil
}

// acquire lease
type MetaAcquireLeaseCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaAcquireLeaseCmd) Reset()                    { *m = MetaAcquireLeaseCmd{} }
func (m *MetaAcquireLeaseCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaAcquireLeaseCmd) ProtoMessage()               {}
func (*MetaAcquireLeaseCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MetaAcquireLeaseCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// continuous query cmd
type MetaCreateContinuousQueryCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Query    string `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
}

func (m *MetaCreateContinuousQueryCmd) Reset()                    { *m = MetaCreateContinuousQueryCmd{} }
func (m *MetaCreateContinuousQueryCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaCreateContinuousQueryCmd) ProtoMessage()               {}
func (*MetaCreateContinuousQueryCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MetaCreateContinuousQueryCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateContinuousQueryCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateContinuousQueryCmd) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type MetaDropContinuousQueryCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropContinuousQueryCmd) Reset()                    { *m = MetaDropContinuousQueryCmd{} }
func (m *MetaDropContinuousQueryCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDropContinuousQueryCmd) ProtoMessage()               {}
func (*MetaDropContinuousQueryCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MetaDropContinuousQueryCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDropContinuousQueryCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// database cmd
type MetaDatabaseCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDatabaseCmd) Reset()                    { *m = MetaDatabaseCmd{} }
func (m *MetaDatabaseCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDatabaseCmd) ProtoMessage()               {}
func (*MetaDatabaseCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MetaDatabaseCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaCreateDatabaseCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaCreateDatabaseCmd) Reset()                    { *m = MetaCreateDatabaseCmd{} }
func (m *MetaCreateDatabaseCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaCreateDatabaseCmd) ProtoMessage()               {}
func (*MetaCreateDatabaseCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MetaCreateDatabaseCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaCreateDatabaseWithRetentionPolicyCmd struct {
	Name string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Spec *RetentionPolicySpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
}

func (m *MetaCreateDatabaseWithRetentionPolicyCmd) Reset() {
	*m = MetaCreateDatabaseWithRetentionPolicyCmd{}
}
func (m *MetaCreateDatabaseWithRetentionPolicyCmd) String() string { return proto.CompactTextString(m) }
func (*MetaCreateDatabaseWithRetentionPolicyCmd) ProtoMessage()    {}
func (*MetaCreateDatabaseWithRetentionPolicyCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10}
}

func (m *MetaCreateDatabaseWithRetentionPolicyCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateDatabaseWithRetentionPolicyCmd) GetSpec() *RetentionPolicySpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type MetaDropDatabaseCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropDatabaseCmd) Reset()                    { *m = MetaDropDatabaseCmd{} }
func (m *MetaDropDatabaseCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDropDatabaseCmd) ProtoMessage()               {}
func (*MetaDropDatabaseCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MetaDropDatabaseCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// retention policy
type MetaCreateRetentionPolicyCmd struct {
	Database    string               `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Spec        *RetentionPolicySpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	MakeDefault bool                 `protobuf:"varint,3,opt,name=makeDefault" json:"makeDefault,omitempty"`
}

func (m *MetaCreateRetentionPolicyCmd) Reset()                    { *m = MetaCreateRetentionPolicyCmd{} }
func (m *MetaCreateRetentionPolicyCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaCreateRetentionPolicyCmd) ProtoMessage()               {}
func (*MetaCreateRetentionPolicyCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MetaCreateRetentionPolicyCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateRetentionPolicyCmd) GetSpec() *RetentionPolicySpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *MetaCreateRetentionPolicyCmd) GetMakeDefault() bool {
	if m != nil {
		return m.MakeDefault
	}
	return false
}

type MetaRetentionPolicyCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *MetaRetentionPolicyCmd) Reset()                    { *m = MetaRetentionPolicyCmd{} }
func (m *MetaRetentionPolicyCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaRetentionPolicyCmd) ProtoMessage()               {}
func (*MetaRetentionPolicyCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MetaRetentionPolicyCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaRetentionPolicyCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaDropRetentionPolicyCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropRetentionPolicyCmd) Reset()                    { *m = MetaDropRetentionPolicyCmd{} }
func (m *MetaDropRetentionPolicyCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDropRetentionPolicyCmd) ProtoMessage()               {}
func (*MetaDropRetentionPolicyCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MetaDropRetentionPolicyCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDropRetentionPolicyCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaUpdateRetentionPolicyCmd struct {
	Database    string                 `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Update      *RetentionPolicyUpdate `protobuf:"bytes,3,opt,name=update" json:"update,omitempty"`
	MakeDefault bool                   `protobuf:"varint,4,opt,name=makeDefault" json:"makeDefault,omitempty"`
}

func (m *MetaUpdateRetentionPolicyCmd) Reset()                    { *m = MetaUpdateRetentionPolicyCmd{} }
func (m *MetaUpdateRetentionPolicyCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaUpdateRetentionPolicyCmd) ProtoMessage()               {}
func (*MetaUpdateRetentionPolicyCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MetaUpdateRetentionPolicyCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaUpdateRetentionPolicyCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaUpdateRetentionPolicyCmd) GetUpdate() *RetentionPolicyUpdate {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *MetaUpdateRetentionPolicyCmd) GetMakeDefault() bool {
	if m != nil {
		return m.MakeDefault
	}
	return false
}

// subsription
type MetaCreateSubscriptionCmd struct {
	Database     string   `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Rp           string   `protobuf:"bytes,2,opt,name=rp" json:"rp,omitempty"`
	Name         string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Mode         string   `protobuf:"bytes,4,opt,name=mode" json:"mode,omitempty"`
	Destinations []string `protobuf:"bytes,5,rep,name=destinations" json:"destinations,omitempty"`
}

func (m *MetaCreateSubscriptionCmd) Reset()                    { *m = MetaCreateSubscriptionCmd{} }
func (m *MetaCreateSubscriptionCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaCreateSubscriptionCmd) ProtoMessage()               {}
func (*MetaCreateSubscriptionCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *MetaCreateSubscriptionCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateSubscriptionCmd) GetRp() string {
	if m != nil {
		return m.Rp
	}
	return ""
}

func (m *MetaCreateSubscriptionCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateSubscriptionCmd) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *MetaCreateSubscriptionCmd) GetDestinations() []string {
	if m != nil {
		return m.Destinations
	}
	return nil
}

type MetaDropSubscriptionCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Rp       string `protobuf:"bytes,2,opt,name=rp" json:"rp,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropSubscriptionCmd) Reset()                    { *m = MetaDropSubscriptionCmd{} }
func (m *MetaDropSubscriptionCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDropSubscriptionCmd) ProtoMessage()               {}
func (*MetaDropSubscriptionCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *MetaDropSubscriptionCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDropSubscriptionCmd) GetRp() string {
	if m != nil {
		return m.Rp
	}
	return ""
}

func (m *MetaDropSubscriptionCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// user cmd
type MetaUserCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaUserCmd) Reset()                    { *m = MetaUserCmd{} }
func (m *MetaUserCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaUserCmd) ProtoMessage()               {}
func (*MetaUserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *MetaUserCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaCreateUserCmd struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Admin    bool   `protobuf:"varint,3,opt,name=admin" json:"admin,omitempty"`
}

func (m *MetaCreateUserCmd) Reset()                    { *m = MetaCreateUserCmd{} }
func (m *MetaCreateUserCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaCreateUserCmd) ProtoMessage()               {}
func (*MetaCreateUserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *MetaCreateUserCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateUserCmd) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MetaCreateUserCmd) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type MetaDropUserCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropUserCmd) Reset()                    { *m = MetaDropUserCmd{} }
func (m *MetaDropUserCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDropUserCmd) ProtoMessage()               {}
func (*MetaDropUserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MetaDropUserCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaUpdateUserCmd struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *MetaUpdateUserCmd) Reset()                    { *m = MetaUpdateUserCmd{} }
func (m *MetaUpdateUserCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaUpdateUserCmd) ProtoMessage()               {}
func (*MetaUpdateUserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *MetaUpdateUserCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaUpdateUserCmd) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// user privilege
type MetaSetAdminPrivilegeCmd struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Admin    bool   `protobuf:"varint,2,opt,name=admin" json:"admin,omitempty"`
}

func (m *MetaSetAdminPrivilegeCmd) Reset()                    { *m = MetaSetAdminPrivilegeCmd{} }
func (m *MetaSetAdminPrivilegeCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaSetAdminPrivilegeCmd) ProtoMessage()               {}
func (*MetaSetAdminPrivilegeCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *MetaSetAdminPrivilegeCmd) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaSetAdminPrivilegeCmd) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type MetaSetPrivilegeCmd struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Database  string `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
	Privilege int64  `protobuf:"varint,3,opt,name=privilege" json:"privilege,omitempty"`
}

func (m *MetaSetPrivilegeCmd) Reset()                    { *m = MetaSetPrivilegeCmd{} }
func (m *MetaSetPrivilegeCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaSetPrivilegeCmd) ProtoMessage()               {}
func (*MetaSetPrivilegeCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *MetaSetPrivilegeCmd) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaSetPrivilegeCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaSetPrivilegeCmd) GetPrivilege() int64 {
	if m != nil {
		return m.Privilege
	}
	return 0
}

type MetaUserPrivilegesCmd struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *MetaUserPrivilegesCmd) Reset()                    { *m = MetaUserPrivilegesCmd{} }
func (m *MetaUserPrivilegesCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaUserPrivilegesCmd) ProtoMessage()               {}
func (*MetaUserPrivilegesCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *MetaUserPrivilegesCmd) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type MetaUserPrivilegeCmd struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Database string `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
}

func (m *MetaUserPrivilegeCmd) Reset()                    { *m = MetaUserPrivilegeCmd{} }
func (m *MetaUserPrivilegeCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaUserPrivilegeCmd) ProtoMessage()               {}
func (*MetaUserPrivilegeCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *MetaUserPrivilegeCmd) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaUserPrivilegeCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type MetaAuthenticateCmd struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *MetaAuthenticateCmd) Reset()                    { *m = MetaAuthenticateCmd{} }
func (m *MetaAuthenticateCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaAuthenticateCmd) ProtoMessage()               {}
func (*MetaAuthenticateCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *MetaAuthenticateCmd) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaAuthenticateCmd) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// shard
type MetaShardGroupsByTimeRangeCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Policy   string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	Tmin     int64  `protobuf:"varint,3,opt,name=tmin" json:"tmin,omitempty"`
	Tmax     int64  `protobuf:"varint,4,opt,name=tmax" json:"tmax,omitempty"`
}

func (m *MetaShardGroupsByTimeRangeCmd) Reset()                    { *m = MetaShardGroupsByTimeRangeCmd{} }
func (m *MetaShardGroupsByTimeRangeCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaShardGroupsByTimeRangeCmd) ProtoMessage()               {}
func (*MetaShardGroupsByTimeRangeCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *MetaShardGroupsByTimeRangeCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaShardGroupsByTimeRangeCmd) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *MetaShardGroupsByTimeRangeCmd) GetTmin() int64 {
	if m != nil {
		return m.Tmin
	}
	return 0
}

func (m *MetaShardGroupsByTimeRangeCmd) GetTmax() int64 {
	if m != nil {
		return m.Tmax
	}
	return 0
}

type MetaDropShardCmd struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *MetaDropShardCmd) Reset()                    { *m = MetaDropShardCmd{} }
func (m *MetaDropShardCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDropShardCmd) ProtoMessage()               {}
func (*MetaDropShardCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *MetaDropShardCmd) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MetaCreateShardGroupCmd struct {
	Database  string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Policy    string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *MetaCreateShardGroupCmd) Reset()                    { *m = MetaCreateShardGroupCmd{} }
func (m *MetaCreateShardGroupCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaCreateShardGroupCmd) ProtoMessage()               {}
func (*MetaCreateShardGroupCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *MetaCreateShardGroupCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateShardGroupCmd) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *MetaCreateShardGroupCmd) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type MetaDeleteShardGroupCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Policy   string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	Id       uint64 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
}

func (m *MetaDeleteShardGroupCmd) Reset()                    { *m = MetaDeleteShardGroupCmd{} }
func (m *MetaDeleteShardGroupCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaDeleteShardGroupCmd) ProtoMessage()               {}
func (*MetaDeleteShardGroupCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *MetaDeleteShardGroupCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDeleteShardGroupCmd) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *MetaDeleteShardGroupCmd) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MetaPrecreateShardGroupsCmd struct {
	From int64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   int64 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
}

func (m *MetaPrecreateShardGroupsCmd) Reset()                    { *m = MetaPrecreateShardGroupsCmd{} }
func (m *MetaPrecreateShardGroupsCmd) String() string            { return proto.CompactTextString(m) }
func (*MetaPrecreateShardGroupsCmd) ProtoMessage()               {}
func (*MetaPrecreateShardGroupsCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *MetaPrecreateShardGroupsCmd) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *MetaPrecreateShardGroupsCmd) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

type DataCreateShardCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Policy   string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	ShardID  uint64 `protobuf:"varint,3,opt,name=shardID" json:"shardID,omitempty"`
	Enabled  bool   `protobuf:"varint,4,opt,name=enabled" json:"enabled,omitempty"`
}

func (m *DataCreateShardCmd) Reset()                    { *m = DataCreateShardCmd{} }
func (m *DataCreateShardCmd) String() string            { return proto.CompactTextString(m) }
func (*DataCreateShardCmd) ProtoMessage()               {}
func (*DataCreateShardCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *DataCreateShardCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DataCreateShardCmd) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *DataCreateShardCmd) GetShardID() uint64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *DataCreateShardCmd) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type DataWriteToShardCmd struct {
	ShardID   uint64 `protobuf:"varint,1,opt,name=shardID" json:"shardID,omitempty"`
	PointData []byte `protobuf:"bytes,2,opt,name=pointData,proto3" json:"pointData,omitempty"`
}

func (m *DataWriteToShardCmd) Reset()                    { *m = DataWriteToShardCmd{} }
func (m *DataWriteToShardCmd) String() string            { return proto.CompactTextString(m) }
func (*DataWriteToShardCmd) ProtoMessage()               {}
func (*DataWriteToShardCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *DataWriteToShardCmd) GetShardID() uint64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *DataWriteToShardCmd) GetPointData() []byte {
	if m != nil {
		return m.PointData
	}
	return nil
}

type DataDeleteShardCmd struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DataDeleteShardCmd) Reset()                    { *m = DataDeleteShardCmd{} }
func (m *DataDeleteShardCmd) String() string            { return proto.CompactTextString(m) }
func (*DataDeleteShardCmd) ProtoMessage()               {}
func (*DataDeleteShardCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *DataDeleteShardCmd) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DataShardGroupCmd struct {
	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (m *DataShardGroupCmd) Reset()                    { *m = DataShardGroupCmd{} }
func (m *DataShardGroupCmd) String() string            { return proto.CompactTextString(m) }
func (*DataShardGroupCmd) ProtoMessage()               {}
func (*DataShardGroupCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *DataShardGroupCmd) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type DataDeleteDatabaseCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DataDeleteDatabaseCmd) Reset()                    { *m = DataDeleteDatabaseCmd{} }
func (m *DataDeleteDatabaseCmd) String() string            { return proto.CompactTextString(m) }
func (*DataDeleteDatabaseCmd) ProtoMessage()               {}
func (*DataDeleteDatabaseCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *DataDeleteDatabaseCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DataDeleteRetentionPolicyCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DataDeleteRetentionPolicyCmd) Reset()                    { *m = DataDeleteRetentionPolicyCmd{} }
func (m *DataDeleteRetentionPolicyCmd) String() string            { return proto.CompactTextString(m) }
func (*DataDeleteRetentionPolicyCmd) ProtoMessage()               {}
func (*DataDeleteRetentionPolicyCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *DataDeleteRetentionPolicyCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DataDeleteRetentionPolicyCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DataDeleteMeasurementCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DataDeleteMeasurementCmd) Reset()                    { *m = DataDeleteMeasurementCmd{} }
func (m *DataDeleteMeasurementCmd) String() string            { return proto.CompactTextString(m) }
func (*DataDeleteMeasurementCmd) ProtoMessage()               {}
func (*DataDeleteMeasurementCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *DataDeleteMeasurementCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DataDeleteMeasurementCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DataMeasurementNamesCmd struct {
	User      *UserInfo `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Database  string    `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
	Condition string    `protobuf:"bytes,3,opt,name=condition" json:"condition,omitempty"`
}

func (m *DataMeasurementNamesCmd) Reset()                    { *m = DataMeasurementNamesCmd{} }
func (m *DataMeasurementNamesCmd) String() string            { return proto.CompactTextString(m) }
func (*DataMeasurementNamesCmd) ProtoMessage()               {}
func (*DataMeasurementNamesCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *DataMeasurementNamesCmd) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DataMeasurementNamesCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DataMeasurementNamesCmd) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type DataMeasurementsCardinalityCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
}

func (m *DataMeasurementsCardinalityCmd) Reset()                    { *m = DataMeasurementsCardinalityCmd{} }
func (m *DataMeasurementsCardinalityCmd) String() string            { return proto.CompactTextString(m) }
func (*DataMeasurementsCardinalityCmd) ProtoMessage()               {}
func (*DataMeasurementsCardinalityCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *DataMeasurementsCardinalityCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DataDeleteSeriesCmd struct {
	Database   string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	SourceData []byte `protobuf:"bytes,2,opt,name=sourceData,proto3" json:"sourceData,omitempty"`
	Condition  string `protobuf:"bytes,3,opt,name=condition" json:"condition,omitempty"`
}

func (m *DataDeleteSeriesCmd) Reset()                    { *m = DataDeleteSeriesCmd{} }
func (m *DataDeleteSeriesCmd) String() string            { return proto.CompactTextString(m) }
func (*DataDeleteSeriesCmd) ProtoMessage()               {}
func (*DataDeleteSeriesCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *DataDeleteSeriesCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DataDeleteSeriesCmd) GetSourceData() []byte {
	if m != nil {
		return m.SourceData
	}
	return nil
}

func (m *DataDeleteSeriesCmd) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type DataSeriesCardinalityCmd struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
}

func (m *DataSeriesCardinalityCmd) Reset()                    { *m = DataSeriesCardinalityCmd{} }
func (m *DataSeriesCardinalityCmd) String() string            { return proto.CompactTextString(m) }
func (*DataSeriesCardinalityCmd) ProtoMessage()               {}
func (*DataSeriesCardinalityCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *DataSeriesCardinalityCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DataTagKeysCmd struct {
	User      *UserInfo `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	ShardIDs  []uint64  `protobuf:"varint,2,rep,packed,name=shardIDs" json:"shardIDs,omitempty"`
	Condition string    `protobuf:"bytes,3,opt,name=condition" json:"condition,omitempty"`
}

func (m *DataTagKeysCmd) Reset()                    { *m = DataTagKeysCmd{} }
func (m *DataTagKeysCmd) String() string            { return proto.CompactTextString(m) }
func (*DataTagKeysCmd) ProtoMessage()               {}
func (*DataTagKeysCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *DataTagKeysCmd) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DataTagKeysCmd) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *DataTagKeysCmd) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type DataTagValuesCmd struct {
	User      *UserInfo `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	ShardIDs  []uint64  `protobuf:"varint,2,rep,packed,name=shardIDs" json:"shardIDs,omitempty"`
	Condition string    `protobuf:"bytes,3,opt,name=condition" json:"condition,omitempty"`
}

func (m *DataTagValuesCmd) Reset()                    { *m = DataTagValuesCmd{} }
func (m *DataTagValuesCmd) String() string            { return proto.CompactTextString(m) }
func (*DataTagValuesCmd) ProtoMessage()               {}
func (*DataTagValuesCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *DataTagValuesCmd) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DataTagValuesCmd) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *DataTagValuesCmd) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func init() {
	proto.RegisterType((*OptionalInt64)(nil), "internal.OptionalInt64")
	proto.RegisterType((*OptionalString)(nil), "internal.OptionalString")
	proto.RegisterType((*RetentionPolicySpec)(nil), "internal.RetentionPolicySpec")
	proto.RegisterType((*RetentionPolicyUpdate)(nil), "internal.RetentionPolicyUpdate")
	proto.RegisterType((*UserInfo)(nil), "internal.UserInfo")
	proto.RegisterType((*MetaAcquireLeaseCmd)(nil), "internal.MetaAcquireLeaseCmd")
	proto.RegisterType((*MetaCreateContinuousQueryCmd)(nil), "internal.MetaCreateContinuousQueryCmd")
	proto.RegisterType((*MetaDropContinuousQueryCmd)(nil), "internal.MetaDropContinuousQueryCmd")
	proto.RegisterType((*MetaDatabaseCmd)(nil), "internal.MetaDatabaseCmd")
	proto.RegisterType((*MetaCreateDatabaseCmd)(nil), "internal.MetaCreateDatabaseCmd")
	proto.RegisterType((*MetaCreateDatabaseWithRetentionPolicyCmd)(nil), "internal.MetaCreateDatabaseWithRetentionPolicyCmd")
	proto.RegisterType((*MetaDropDatabaseCmd)(nil), "internal.MetaDropDatabaseCmd")
	proto.RegisterType((*MetaCreateRetentionPolicyCmd)(nil), "internal.MetaCreateRetentionPolicyCmd")
	proto.RegisterType((*MetaRetentionPolicyCmd)(nil), "internal.MetaRetentionPolicyCmd")
	proto.RegisterType((*MetaDropRetentionPolicyCmd)(nil), "internal.MetaDropRetentionPolicyCmd")
	proto.RegisterType((*MetaUpdateRetentionPolicyCmd)(nil), "internal.MetaUpdateRetentionPolicyCmd")
	proto.RegisterType((*MetaCreateSubscriptionCmd)(nil), "internal.MetaCreateSubscriptionCmd")
	proto.RegisterType((*MetaDropSubscriptionCmd)(nil), "internal.MetaDropSubscriptionCmd")
	proto.RegisterType((*MetaUserCmd)(nil), "internal.MetaUserCmd")
	proto.RegisterType((*MetaCreateUserCmd)(nil), "internal.MetaCreateUserCmd")
	proto.RegisterType((*MetaDropUserCmd)(nil), "internal.MetaDropUserCmd")
	proto.RegisterType((*MetaUpdateUserCmd)(nil), "internal.MetaUpdateUserCmd")
	proto.RegisterType((*MetaSetAdminPrivilegeCmd)(nil), "internal.MetaSetAdminPrivilegeCmd")
	proto.RegisterType((*MetaSetPrivilegeCmd)(nil), "internal.MetaSetPrivilegeCmd")
	proto.RegisterType((*MetaUserPrivilegesCmd)(nil), "internal.MetaUserPrivilegesCmd")
	proto.RegisterType((*MetaUserPrivilegeCmd)(nil), "internal.MetaUserPrivilegeCmd")
	proto.RegisterType((*MetaAuthenticateCmd)(nil), "internal.MetaAuthenticateCmd")
	proto.RegisterType((*MetaShardGroupsByTimeRangeCmd)(nil), "internal.MetaShardGroupsByTimeRangeCmd")
	proto.RegisterType((*MetaDropShardCmd)(nil), "internal.MetaDropShardCmd")
	proto.RegisterType((*MetaCreateShardGroupCmd)(nil), "internal.MetaCreateShardGroupCmd")
	proto.RegisterType((*MetaDeleteShardGroupCmd)(nil), "internal.MetaDeleteShardGroupCmd")
	proto.RegisterType((*MetaPrecreateShardGroupsCmd)(nil), "internal.MetaPrecreateShardGroupsCmd")
	proto.RegisterType((*DataCreateShardCmd)(nil), "internal.DataCreateShardCmd")
	proto.RegisterType((*DataWriteToShardCmd)(nil), "internal.DataWriteToShardCmd")
	proto.RegisterType((*DataDeleteShardCmd)(nil), "internal.DataDeleteShardCmd")
	proto.RegisterType((*DataShardGroupCmd)(nil), "internal.DataShardGroupCmd")
	proto.RegisterType((*DataDeleteDatabaseCmd)(nil), "internal.DataDeleteDatabaseCmd")
	proto.RegisterType((*DataDeleteRetentionPolicyCmd)(nil), "internal.DataDeleteRetentionPolicyCmd")
	proto.RegisterType((*DataDeleteMeasurementCmd)(nil), "internal.DataDeleteMeasurementCmd")
	proto.RegisterType((*DataMeasurementNamesCmd)(nil), "internal.DataMeasurementNamesCmd")
	proto.RegisterType((*DataMeasurementsCardinalityCmd)(nil), "internal.DataMeasurementsCardinalityCmd")
	proto.RegisterType((*DataDeleteSeriesCmd)(nil), "internal.DataDeleteSeriesCmd")
	proto.RegisterType((*DataSeriesCardinalityCmd)(nil), "internal.DataSeriesCardinalityCmd")
	proto.RegisterType((*DataTagKeysCmd)(nil), "internal.DataTagKeysCmd")
	proto.RegisterType((*DataTagValuesCmd)(nil), "internal.DataTagValuesCmd")
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x52, 0x1c, 0xc5,
	0x17, 0xaf, 0x99, 0x59, 0xf8, 0xb3, 0x87, 0xfc, 0x09, 0x99, 0x90, 0x30, 0x22, 0x89, 0x9b, 0x2e,
	0x63, 0xad, 0xa5, 0x45, 0x95, 0x60, 0x45, 0xcb, 0xd2, 0x0b, 0x02, 0x56, 0x44, 0x01, 0x71, 0x96,
	0x98, 0xca, 0x85, 0x17, 0xcd, 0xcc, 0x01, 0xba, 0x98, 0x2f, 0xba, 0x7b, 0xd0, 0xad, 0xf8, 0x0e,
	0x5e, 0xf8, 0x14, 0x3e, 0x87, 0x97, 0xbe, 0x90, 0x97, 0x56, 0xf7, 0xf4, 0x7c, 0xb0, 0xec, 0x32,
	0xe1, 0xa3, 0x72, 0xd7, 0xa7, 0xe7, 0x9c, 0xf3, 0xfb, 0x9d, 0x8f, 0x3e, 0xdd, 0x03, 0xdd, 0x20,
	0x0e, 0x57, 0x32, 0x9e, 0xca, 0xd4, 0x9d, 0x61, 0x89, 0x44, 0x9e, 0xd0, 0x88, 0x3c, 0x81, 0xff,
	0xff, 0x98, 0x49, 0x96, 0x26, 0x34, 0xda, 0x4a, 0xe4, 0xb3, 0xcf, 0xdd, 0x79, 0x70, 0xce, 0x68,
	0xe4, 0x59, 0x3d, 0xab, 0xef, 0xf8, 0x6a, 0x49, 0x08, 0xcc, 0x95, 0x2a, 0x03, 0xc9, 0x59, 0x72,
	0xd4, 0xd4, 0xe9, 0x16, 0x3a, 0x7f, 0x5b, 0x70, 0xdf, 0x47, 0x89, 0x89, 0xd2, 0xdb, 0x4b, 0x23,
	0x16, 0x0c, 0x07, 0x19, 0x06, 0xae, 0x0b, 0x9d, 0x84, 0xc6, 0x68, 0x54, 0xf5, 0xda, 0x5d, 0x83,
	0x19, 0x8e, 0x59, 0xc4, 0x02, 0xba, 0xeb, 0xd9, 0x3d, 0xab, 0x3f, 0xbb, 0xba, 0xb8, 0x52, 0xf2,
	0x59, 0x39, 0x47, 0xc6, 0xaf, 0x14, 0x95, 0x51, 0x98, 0x73, 0xaa, 0x3e, 0x7a, 0x4e, 0x8b, 0x51,
	0xa9, 0xe8, 0xae, 0x80, 0x3b, 0x38, 0xa6, 0x3c, 0x7c, 0xc1, 0xd3, 0x3c, 0xdb, 0x2c, 0xcd, 0x3b,
	0x3a, 0xb4, 0x31, 0x5f, 0xc8, 0xbf, 0x16, 0x3c, 0x18, 0x89, 0xe2, 0x65, 0x16, 0x52, 0x89, 0xee,
	0xa7, 0x8d, 0x38, 0x66, 0x57, 0xbd, 0x8b, 0xd0, 0x45, 0x66, 0xde, 0x79, 0x84, 0x2f, 0x26, 0x46,
	0x78, 0x89, 0xf9, 0xb8, 0xd0, 0xff, 0xb1, 0x60, 0xe6, 0xa5, 0x40, 0xbe, 0x95, 0x1c, 0xa6, 0x63,
	0xab, 0xe6, 0x42, 0xe7, 0x98, 0x8a, 0x63, 0x1d, 0x4f, 0xd7, 0xd7, 0x6b, 0x77, 0x01, 0xa6, 0x68,
	0x18, 0xb3, 0x82, 0xef, 0x8c, 0x5f, 0x08, 0xee, 0x73, 0x80, 0x8c, 0xb3, 0x33, 0x16, 0xe1, 0x11,
	0x0a, 0xaf, 0xd3, 0x73, 0xfa, 0xb3, 0xab, 0xa4, 0xe6, 0x52, 0xa2, 0xac, 0xec, 0x55, 0x4a, 0xdf,
	0x26, 0x92, 0x0f, 0xfd, 0x86, 0xd5, 0xd2, 0x37, 0x70, 0x77, 0xe4, 0xb3, 0x6a, 0xba, 0x13, 0x1c,
	0x96, 0x4d, 0x77, 0x82, 0x43, 0x05, 0x7f, 0x46, 0xa3, 0x1c, 0x35, 0x27, 0xc7, 0x2f, 0x84, 0xaf,
	0xec, 0x2f, 0x2d, 0xf2, 0x31, 0xdc, 0xdf, 0x41, 0x49, 0xd7, 0x83, 0xd3, 0x9c, 0x71, 0xdc, 0x46,
	0x2a, 0x70, 0x23, 0x0e, 0xc7, 0xc5, 0x45, 0x42, 0x58, 0x56, 0xaa, 0x1b, 0x1c, 0xa9, 0xc4, 0x8d,
	0x34, 0x91, 0x2c, 0xc9, 0xd3, 0x5c, 0xfc, 0x94, 0x23, 0x1f, 0x2a, 0x9b, 0x25, 0x98, 0x09, 0xa9,
	0xa4, 0x07, 0x54, 0x94, 0x76, 0x95, 0x5c, 0xf9, 0xb3, 0x1b, 0x79, 0x5a, 0x80, 0xa9, 0x53, 0x65,
	0xab, 0x73, 0xd2, 0xf5, 0x0b, 0x81, 0x6c, 0xc3, 0x92, 0x42, 0xd9, 0xe4, 0x69, 0x76, 0x73, 0x0c,
	0xf2, 0x14, 0xee, 0x6a, 0x6f, 0x46, 0x67, 0x52, 0x68, 0x9f, 0xc0, 0x83, 0x3a, 0xb4, 0x36, 0xe5,
	0x53, 0xe8, 0x5f, 0x54, 0x7e, 0xc5, 0xe4, 0xf1, 0xc8, 0x81, 0x98, 0x60, 0xef, 0x7e, 0x06, 0x1d,
	0x91, 0x61, 0x60, 0xfa, 0xfd, 0x51, 0x5d, 0xef, 0x31, 0x63, 0xc1, 0xd7, 0xaa, 0x65, 0x95, 0x54,
	0x52, 0xda, 0xd8, 0xfd, 0x61, 0x35, 0xcb, 0x34, 0x86, 0xd2, 0x65, 0x29, 0xbc, 0x3a, 0x35, 0xb7,
	0x07, 0xb3, 0x31, 0x3d, 0xc1, 0x4d, 0x3c, 0xa4, 0x79, 0x24, 0x4d, 0x7f, 0x37, 0xb7, 0xc8, 0x77,
	0xf0, 0x50, 0x11, 0xba, 0x22, 0x95, 0x71, 0xd5, 0x6c, 0xf4, 0xc6, 0x2d, 0x78, 0xfb, 0xcb, 0x64,
	0xaa, 0x18, 0x5c, 0x37, 0x77, 0xe8, 0x7e, 0x01, 0xd3, 0xb9, 0xf6, 0x65, 0xa6, 0xd2, 0x07, 0x13,
	0xf3, 0x67, 0x20, 0x8d, 0xfa, 0x68, 0x0e, 0x3b, 0x17, 0x73, 0xf8, 0xa7, 0x05, 0xef, 0xd5, 0x55,
	0x1d, 0xe4, 0x07, 0x22, 0xe0, 0x4c, 0x8f, 0xaa, 0x36, 0xa2, 0x73, 0x60, 0xf3, 0xcc, 0xd0, 0xb4,
	0x79, 0x56, 0x11, 0x77, 0xce, 0x4f, 0xac, 0x38, 0x0d, 0x51, 0x03, 0x77, 0x7d, 0xbd, 0x76, 0x09,
	0xdc, 0x09, 0x51, 0x48, 0x96, 0xe8, 0xa9, 0x27, 0xbc, 0xa9, 0x9e, 0xd3, 0xef, 0xfa, 0xe7, 0xf6,
	0xc8, 0x6b, 0x58, 0x2c, 0xeb, 0x71, 0xcb, 0x94, 0xc8, 0x13, 0x98, 0xd5, 0xb5, 0x11, 0xc8, 0x27,
	0x75, 0xfa, 0x6b, 0xb8, 0x57, 0xa7, 0xe4, 0x12, 0x45, 0xc5, 0x25, 0xa3, 0x42, 0xfc, 0x9a, 0xf2,
	0xd0, 0xa0, 0x56, 0xf2, 0xf8, 0xc1, 0x5c, 0x8d, 0x0d, 0x9e, 0x66, 0x97, 0x31, 0xd8, 0x28, 0x18,
	0x14, 0xd5, 0xbc, 0x26, 0x03, 0xb2, 0x0d, 0x9e, 0x72, 0x32, 0x40, 0xb9, 0xae, 0xb0, 0xab, 0x61,
	0x6e, 0xb2, 0x98, 0x0b, 0xd5, 0x41, 0x95, 0xbf, 0x4a, 0xae, 0x99, 0xdb, 0x4d, 0xe6, 0x27, 0xc5,
	0xa4, 0x18, 0xa0, 0x7c, 0x6b, 0x47, 0xcd, 0x52, 0xd9, 0x23, 0xa5, 0x5a, 0x86, 0x6e, 0x75, 0xd7,
	0xe8, 0x14, 0x39, 0x7e, 0xbd, 0x41, 0xd6, 0x8a, 0xb1, 0xa9, 0x22, 0xaf, 0xef, 0xa0, 0x16, 0x38,
	0xb2, 0x0b, 0x0b, 0x17, 0x8c, 0x6e, 0x40, 0x91, 0xec, 0x98, 0x1b, 0x2c, 0x97, 0xc7, 0xea, 0x88,
	0x05, 0xea, 0x72, 0x6a, 0x77, 0x37, 0xb1, 0x1c, 0x6f, 0xe0, 0x91, 0x4e, 0x60, 0x75, 0xf1, 0x8b,
	0xe7, 0xc3, 0x7d, 0x16, 0xa3, 0x4f, 0x93, 0x8a, 0xe7, 0xc4, 0xce, 0x7e, 0x08, 0xd3, 0x99, 0x3e,
	0xe0, 0xc6, 0xad, 0x91, 0x54, 0x4f, 0xc8, 0xb2, 0xc9, 0x1c, 0x5f, 0xaf, 0x8b, 0x3d, 0xfa, 0x9b,
	0x79, 0x64, 0xe9, 0x35, 0x21, 0x30, 0x5f, 0x1d, 0x28, 0x45, 0x40, 0xe1, 0xcd, 0x81, 0xcd, 0x42,
	0x8d, 0xd4, 0xf1, 0x6d, 0x16, 0x92, 0x93, 0xe2, 0xd0, 0x99, 0x49, 0x50, 0xd1, 0xbc, 0x2e, 0xb5,
	0x65, 0xe8, 0x4a, 0x16, 0xa3, 0x90, 0x34, 0xce, 0xca, 0x0a, 0x57, 0x1b, 0xe4, 0x17, 0x73, 0xc2,
	0x31, 0xc2, 0xdb, 0x00, 0x2b, 0x62, 0x71, 0xaa, 0x58, 0xd6, 0xe1, 0x7d, 0xe5, 0x7e, 0x8f, 0x63,
	0x30, 0x12, 0x8e, 0x30, 0x47, 0xe9, 0x90, 0xa7, 0xb1, 0x79, 0x62, 0xeb, 0xb5, 0x72, 0x21, 0x53,
	0xf3, 0x8e, 0xb1, 0x65, 0x4a, 0x7e, 0x07, 0x57, 0x5d, 0x89, 0x8d, 0x74, 0x5c, 0x97, 0x9c, 0x07,
	0xff, 0x13, 0xca, 0x7e, 0x6b, 0xd3, 0x30, 0x2c, 0x45, 0xf5, 0x05, 0x13, 0x7a, 0x10, 0x61, 0x68,
	0x66, 0x73, 0x29, 0xaa, 0xe6, 0x53, 0xe8, 0xaf, 0x38, 0x93, 0xb8, 0x9f, 0x56, 0xf0, 0x0d, 0x57,
	0xd6, 0x79, 0x57, 0xea, 0x40, 0xa5, 0x2c, 0x91, 0xca, 0x4a, 0xe3, 0xdf, 0xf1, 0xeb, 0x0d, 0xf2,
	0x61, 0x11, 0x4c, 0x23, 0xdd, 0xe3, 0x3a, 0xe0, 0x29, 0xdc, 0x53, 0x5a, 0xe7, 0xcb, 0x31, 0x0f,
	0x0e, 0x0b, 0x85, 0x67, 0xf5, 0x9c, 0x7e, 0xc7, 0x57, 0x4b, 0xf5, 0xa8, 0xa9, 0x9d, 0xb5, 0x3d,
	0x1b, 0x76, 0x61, 0xb9, 0x56, 0xbe, 0x85, 0xcb, 0xf5, 0x7b, 0xf0, 0x6a, 0x7f, 0x3b, 0x48, 0x45,
	0xce, 0x31, 0xc6, 0x44, 0x5e, 0xc7, 0xd7, 0x1b, 0x58, 0x54, 0xbe, 0x1a, 0x5e, 0x76, 0x69, 0x5c,
	0x0c, 0x9a, 0x8f, 0xa0, 0xa3, 0x4e, 0xb5, 0xf9, 0xdb, 0x70, 0x2f, 0xbe, 0x9d, 0x7d, 0xfd, 0xbd,
	0x6d, 0xc6, 0x05, 0x69, 0x12, 0xb2, 0xea, 0x7f, 0xa2, 0xeb, 0xd7, 0x1b, 0xe4, 0x6b, 0x78, 0x3c,
	0x02, 0x2e, 0x36, 0x28, 0x0f, 0x59, 0x42, 0x23, 0x26, 0xdb, 0x52, 0x43, 0xd2, 0xa2, 0x3f, 0x4c,
	0x41, 0x91, 0xb3, 0x6a, 0x3e, 0x4e, 0xcc, 0xc0, 0x63, 0x00, 0x91, 0xe6, 0x3c, 0xc0, 0x46, 0x8b,
	0x34, 0x76, 0x5a, 0xe8, 0x3e, 0x2b, 0xf2, 0x6e, 0xa0, 0xde, 0x9e, 0x28, 0x87, 0x39, 0x65, 0xb7,
	0x4f, 0x8f, 0x7e, 0xc0, 0xe1, 0x55, 0x53, 0x6b, 0x9a, 0x5b, 0x78, 0xb6, 0xee, 0xbe, 0x4a, 0x6e,
	0xe1, 0x2a, 0x61, 0xde, 0x60, 0xfe, 0xac, 0xfe, 0x47, 0xde, 0x0d, 0xea, 0xc1, 0xb4, 0xfe, 0xb1,
	0x5f, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x19, 0x4f, 0xc5, 0xf1, 0xe5, 0x0f, 0x00, 0x00,
}
