// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	common.proto
	cluster.proto
	meta.proto
	store.proto

It has these top-level messages:
	Empty
	Leader
	Result
	UserInfo
	OptionalInt64
	OptionalString
	Node
	ClusterJoinReq
	ClusterJoinResp
	ClusterRemoveReq
	ClusterRemoveResp
	MetaRetentionPolicySpec
	MetaRetentionPolicyUpdate
	MetaAcquireLeaseReq
	MetaCreateContinuousQueryReq
	MetaDropContinuousQueryReq
	MetaDatabaseReq
	MetaCreateDatabaseReq
	MetaCreateDatabaseWithRetentionPolicyReq
	MetaDropDatabaseReq
	MetaCreateRetentionPolicyReq
	MetaRetentionPolicyReq
	MetaDropRetentionPolicyReq
	MetaUpdateRetentionPolicyReq
	MetaCreateSubscriptionReq
	MetaDropSubscriptionReq
	MetaUserReq
	MetaCreateUserReq
	MetaDropUserReq
	MetaUpdateUserReq
	MetaSetAdminPrivilegeReq
	MetaSetPrivilegeReq
	MetaUserPrivilegesReq
	MetaUserPrivilegeReq
	MetaAuthenticateReq
	MetaShardGroupsByTimeRangeReq
	MetaDropShardReq
	MetaCreateShardGroupReq
	MetaDeleteShardGroupReq
	MetaPrecreateShardGroupsReq
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Code int32

const (
	Code_CodeUnknown           Code = 0
	Code_CodeOK                Code = 1
	Code_CodeNotLeader         Code = 1001
	Code_CodeErrLeadershipLost Code = 1002
)

var Code_name = map[int32]string{
	0:    "CodeUnknown",
	1:    "CodeOK",
	1001: "CodeNotLeader",
	1002: "CodeErrLeadershipLost",
}
var Code_value = map[string]int32{
	"CodeUnknown":           0,
	"CodeOK":                1,
	"CodeNotLeader":         1001,
	"CodeErrLeadershipLost": 1002,
}

func (x Code) String() string {
	return proto1.EnumName(Code_name, int32(x))
}
func (Code) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Leader struct {
	Available bool   `protobuf:"varint,1,opt,name=available" json:"available,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Leader) Reset()                    { *m = Leader{} }
func (m *Leader) String() string            { return proto1.CompactTextString(m) }
func (*Leader) ProtoMessage()               {}
func (*Leader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Leader) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Leader) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Result struct {
	Code    Code   `protobuf:"varint,1,opt,name=code,enum=proto.Code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto1.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Result) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_CodeUnknown
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserInfo struct {
	Name       string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hash       string           `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Admin      bool             `protobuf:"varint,3,opt,name=admin" json:"admin,omitempty"`
	Privileges map[string]int64 `protobuf:"bytes,4,rep,name=privileges" json:"privileges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto1.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *UserInfo) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *UserInfo) GetPrivileges() map[string]int64 {
	if m != nil {
		return m.Privileges
	}
	return nil
}

type OptionalInt64 struct {
	Val int64 `protobuf:"varint,1,opt,name=val" json:"val,omitempty"`
}

func (m *OptionalInt64) Reset()                    { *m = OptionalInt64{} }
func (m *OptionalInt64) String() string            { return proto1.CompactTextString(m) }
func (*OptionalInt64) ProtoMessage()               {}
func (*OptionalInt64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OptionalInt64) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

type OptionalString struct {
	Val string `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
}

func (m *OptionalString) Reset()                    { *m = OptionalString{} }
func (m *OptionalString) String() string            { return proto1.CompactTextString(m) }
func (*OptionalString) ProtoMessage()               {}
func (*OptionalString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OptionalString) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*Leader)(nil), "proto.Leader")
	proto1.RegisterType((*Result)(nil), "proto.Result")
	proto1.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto1.RegisterType((*OptionalInt64)(nil), "proto.OptionalInt64")
	proto1.RegisterType((*OptionalString)(nil), "proto.OptionalString")
	proto1.RegisterEnum("proto.Code", Code_name, Code_value)
}

func init() { proto1.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xd1, 0x8a, 0xda, 0x40,
	0x14, 0x6d, 0x4c, 0x4c, 0xcc, 0xb5, 0x6a, 0x18, 0x5a, 0x08, 0x52, 0xd0, 0xe6, 0x49, 0xfa, 0xe0,
	0x83, 0x2d, 0xa5, 0x14, 0x4a, 0x17, 0xc4, 0x07, 0x59, 0x59, 0x97, 0x11, 0x3f, 0x60, 0x34, 0xb3,
	0x1a, 0x4c, 0x66, 0xc2, 0xcc, 0x98, 0xc5, 0x3f, 0xdc, 0x5f, 0xd9, 0xfd, 0x8a, 0x65, 0x66, 0x92,
	0x5d, 0xd9, 0xa7, 0x39, 0xe7, 0xdc, 0x73, 0xee, 0xbd, 0xb9, 0x81, 0xcf, 0x7b, 0x5e, 0x14, 0x9c,
	0x4d, 0x4b, 0xc1, 0x15, 0x47, 0x6d, 0xf3, 0x24, 0x01, 0xb4, 0x17, 0x45, 0xa9, 0x2e, 0xc9, 0x0d,
	0xf8, 0x2b, 0x4a, 0x52, 0x2a, 0xd0, 0x37, 0x08, 0x49, 0x45, 0xb2, 0x9c, 0xec, 0x72, 0x1a, 0x3b,
	0x63, 0x67, 0xd2, 0xc1, 0xef, 0x02, 0x8a, 0x21, 0x20, 0x69, 0x2a, 0xa8, 0x94, 0x71, 0x6b, 0xec,
	0x4c, 0x42, 0xdc, 0xd0, 0x64, 0x0e, 0x3e, 0xa6, 0xf2, 0x9c, 0x2b, 0x34, 0x02, 0x6f, 0xcf, 0x53,
	0x1b, 0xee, 0xcf, 0xba, 0x76, 0xe2, 0x74, 0xce, 0x53, 0x8a, 0x4d, 0x41, 0x37, 0x29, 0xa8, 0x94,
	0xe4, 0x40, 0x9b, 0x26, 0x35, 0x4d, 0x9e, 0x1c, 0xe8, 0x6c, 0x25, 0x15, 0x4b, 0xf6, 0xc0, 0x11,
	0x02, 0x8f, 0x91, 0xc2, 0xf6, 0x09, 0xb1, 0xc1, 0x5a, 0x3b, 0x12, 0x79, 0xac, 0x73, 0x06, 0xa3,
	0x2f, 0xd0, 0x26, 0x69, 0x91, 0xb1, 0xd8, 0x35, 0xdb, 0x5a, 0x82, 0xfe, 0x03, 0x94, 0x22, 0xab,
	0xb2, 0x9c, 0x1e, 0xa8, 0x8c, 0xbd, 0xb1, 0x3b, 0xe9, 0xce, 0x46, 0xf5, 0x2e, 0xcd, 0x88, 0xe9,
	0xfd, 0x9b, 0x63, 0xc1, 0x94, 0xb8, 0xe0, 0xab, 0xc8, 0xf0, 0x1f, 0x0c, 0x3e, 0x94, 0x51, 0x04,
	0xee, 0x89, 0x5e, 0xea, 0x85, 0x34, 0xd4, 0xb3, 0x2b, 0x92, 0x9f, 0xed, 0x87, 0xb8, 0xd8, 0x92,
	0xbf, 0xad, 0x3f, 0x4e, 0xf2, 0x1d, 0x7a, 0xeb, 0x52, 0x65, 0x9c, 0x91, 0x7c, 0xc9, 0xd4, 0xef,
	0x5f, 0x3a, 0x5c, 0x91, 0xdc, 0x84, 0x5d, 0xac, 0x61, 0x92, 0x40, 0xbf, 0xb1, 0x6c, 0x94, 0xc8,
	0xd8, 0xe1, 0xda, 0x13, 0x1a, 0xcf, 0x8f, 0x0d, 0x78, 0xfa, 0x72, 0x68, 0x00, 0x5d, 0xfd, 0x6e,
	0xd9, 0x89, 0xf1, 0x47, 0x16, 0x7d, 0x42, 0x00, 0xbe, 0x16, 0xd6, 0xb7, 0x91, 0x83, 0x10, 0xf4,
	0x34, 0xbe, 0xe3, 0xca, 0xfe, 0xc4, 0xe8, 0x39, 0x40, 0x43, 0xf8, 0xaa, 0xb5, 0x85, 0x10, 0x56,
	0x93, 0xc7, 0xac, 0x5c, 0x71, 0xa9, 0xa2, 0x97, 0x60, 0xe7, 0x9b, 0x33, 0xfc, 0x7c, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x74, 0x47, 0x5c, 0x6d, 0x14, 0x02, 0x00, 0x00,
}
