// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MetaRetentionPolicySpec struct {
	Name               string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReplicaN           *OptionalInt64 `protobuf:"bytes,2,opt,name=replicaN" json:"replicaN,omitempty"`
	Duration           *OptionalInt64 `protobuf:"bytes,3,opt,name=duration" json:"duration,omitempty"`
	ShardGroupDuration int64          `protobuf:"varint,4,opt,name=ShardGroupDuration" json:"ShardGroupDuration,omitempty"`
}

func (m *MetaRetentionPolicySpec) Reset()                    { *m = MetaRetentionPolicySpec{} }
func (m *MetaRetentionPolicySpec) String() string            { return proto1.CompactTextString(m) }
func (*MetaRetentionPolicySpec) ProtoMessage()               {}
func (*MetaRetentionPolicySpec) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *MetaRetentionPolicySpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaRetentionPolicySpec) GetReplicaN() *OptionalInt64 {
	if m != nil {
		return m.ReplicaN
	}
	return nil
}

func (m *MetaRetentionPolicySpec) GetDuration() *OptionalInt64 {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *MetaRetentionPolicySpec) GetShardGroupDuration() int64 {
	if m != nil {
		return m.ShardGroupDuration
	}
	return 0
}

type MetaRetentionPolicyUpdate struct {
	Name               *OptionalString `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReplicaN           *OptionalInt64  `protobuf:"bytes,2,opt,name=replicaN" json:"replicaN,omitempty"`
	Duration           *OptionalInt64  `protobuf:"bytes,3,opt,name=duration" json:"duration,omitempty"`
	ShardGroupDuration *OptionalInt64  `protobuf:"bytes,4,opt,name=ShardGroupDuration" json:"ShardGroupDuration,omitempty"`
}

func (m *MetaRetentionPolicyUpdate) Reset()                    { *m = MetaRetentionPolicyUpdate{} }
func (m *MetaRetentionPolicyUpdate) String() string            { return proto1.CompactTextString(m) }
func (*MetaRetentionPolicyUpdate) ProtoMessage()               {}
func (*MetaRetentionPolicyUpdate) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *MetaRetentionPolicyUpdate) GetName() *OptionalString {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MetaRetentionPolicyUpdate) GetReplicaN() *OptionalInt64 {
	if m != nil {
		return m.ReplicaN
	}
	return nil
}

func (m *MetaRetentionPolicyUpdate) GetDuration() *OptionalInt64 {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *MetaRetentionPolicyUpdate) GetShardGroupDuration() *OptionalInt64 {
	if m != nil {
		return m.ShardGroupDuration
	}
	return nil
}

// acquire lease
type MetaAcquireLeaseReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaAcquireLeaseReq) Reset()                    { *m = MetaAcquireLeaseReq{} }
func (m *MetaAcquireLeaseReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaAcquireLeaseReq) ProtoMessage()               {}
func (*MetaAcquireLeaseReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *MetaAcquireLeaseReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// continuous query cmd
type MetaCreateContinuousQueryReq struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Query    string `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
}

func (m *MetaCreateContinuousQueryReq) Reset()                    { *m = MetaCreateContinuousQueryReq{} }
func (m *MetaCreateContinuousQueryReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaCreateContinuousQueryReq) ProtoMessage()               {}
func (*MetaCreateContinuousQueryReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *MetaCreateContinuousQueryReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateContinuousQueryReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateContinuousQueryReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type MetaDropContinuousQueryReq struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropContinuousQueryReq) Reset()                    { *m = MetaDropContinuousQueryReq{} }
func (m *MetaDropContinuousQueryReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDropContinuousQueryReq) ProtoMessage()               {}
func (*MetaDropContinuousQueryReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *MetaDropContinuousQueryReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDropContinuousQueryReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// database cmd
type MetaDatabaseReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDatabaseReq) Reset()                    { *m = MetaDatabaseReq{} }
func (m *MetaDatabaseReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDatabaseReq) ProtoMessage()               {}
func (*MetaDatabaseReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *MetaDatabaseReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaCreateDatabaseReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaCreateDatabaseReq) Reset()                    { *m = MetaCreateDatabaseReq{} }
func (m *MetaCreateDatabaseReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaCreateDatabaseReq) ProtoMessage()               {}
func (*MetaCreateDatabaseReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *MetaCreateDatabaseReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaCreateDatabaseWithRetentionPolicyReq struct {
	Name string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Spec *MetaRetentionPolicySpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
}

func (m *MetaCreateDatabaseWithRetentionPolicyReq) Reset() {
	*m = MetaCreateDatabaseWithRetentionPolicyReq{}
}
func (m *MetaCreateDatabaseWithRetentionPolicyReq) String() string { return proto1.CompactTextString(m) }
func (*MetaCreateDatabaseWithRetentionPolicyReq) ProtoMessage()    {}
func (*MetaCreateDatabaseWithRetentionPolicyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{7}
}

func (m *MetaCreateDatabaseWithRetentionPolicyReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateDatabaseWithRetentionPolicyReq) GetSpec() *MetaRetentionPolicySpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type MetaDropDatabaseReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropDatabaseReq) Reset()                    { *m = MetaDropDatabaseReq{} }
func (m *MetaDropDatabaseReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDropDatabaseReq) ProtoMessage()               {}
func (*MetaDropDatabaseReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *MetaDropDatabaseReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// retention policy
type MetaCreateRetentionPolicyReq struct {
	Database    string                   `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Spec        *MetaRetentionPolicySpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	MakeDefault bool                     `protobuf:"varint,3,opt,name=makeDefault" json:"makeDefault,omitempty"`
}

func (m *MetaCreateRetentionPolicyReq) Reset()                    { *m = MetaCreateRetentionPolicyReq{} }
func (m *MetaCreateRetentionPolicyReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaCreateRetentionPolicyReq) ProtoMessage()               {}
func (*MetaCreateRetentionPolicyReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *MetaCreateRetentionPolicyReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateRetentionPolicyReq) GetSpec() *MetaRetentionPolicySpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *MetaCreateRetentionPolicyReq) GetMakeDefault() bool {
	if m != nil {
		return m.MakeDefault
	}
	return false
}

type MetaRetentionPolicyReq struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *MetaRetentionPolicyReq) Reset()                    { *m = MetaRetentionPolicyReq{} }
func (m *MetaRetentionPolicyReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaRetentionPolicyReq) ProtoMessage()               {}
func (*MetaRetentionPolicyReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *MetaRetentionPolicyReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaRetentionPolicyReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaDropRetentionPolicyReq struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropRetentionPolicyReq) Reset()                    { *m = MetaDropRetentionPolicyReq{} }
func (m *MetaDropRetentionPolicyReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDropRetentionPolicyReq) ProtoMessage()               {}
func (*MetaDropRetentionPolicyReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *MetaDropRetentionPolicyReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDropRetentionPolicyReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaUpdateRetentionPolicyReq struct {
	Database    string                     `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Update      *MetaRetentionPolicyUpdate `protobuf:"bytes,3,opt,name=update" json:"update,omitempty"`
	MakeDefault bool                       `protobuf:"varint,4,opt,name=makeDefault" json:"makeDefault,omitempty"`
}

func (m *MetaUpdateRetentionPolicyReq) Reset()                    { *m = MetaUpdateRetentionPolicyReq{} }
func (m *MetaUpdateRetentionPolicyReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaUpdateRetentionPolicyReq) ProtoMessage()               {}
func (*MetaUpdateRetentionPolicyReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *MetaUpdateRetentionPolicyReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaUpdateRetentionPolicyReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaUpdateRetentionPolicyReq) GetUpdate() *MetaRetentionPolicyUpdate {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *MetaUpdateRetentionPolicyReq) GetMakeDefault() bool {
	if m != nil {
		return m.MakeDefault
	}
	return false
}

// subsription
type MetaCreateSubscriptionReq struct {
	Database     string   `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Rp           string   `protobuf:"bytes,2,opt,name=rp" json:"rp,omitempty"`
	Name         string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Mode         string   `protobuf:"bytes,4,opt,name=mode" json:"mode,omitempty"`
	Destinations []string `protobuf:"bytes,5,rep,name=destinations" json:"destinations,omitempty"`
}

func (m *MetaCreateSubscriptionReq) Reset()                    { *m = MetaCreateSubscriptionReq{} }
func (m *MetaCreateSubscriptionReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaCreateSubscriptionReq) ProtoMessage()               {}
func (*MetaCreateSubscriptionReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *MetaCreateSubscriptionReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateSubscriptionReq) GetRp() string {
	if m != nil {
		return m.Rp
	}
	return ""
}

func (m *MetaCreateSubscriptionReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateSubscriptionReq) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *MetaCreateSubscriptionReq) GetDestinations() []string {
	if m != nil {
		return m.Destinations
	}
	return nil
}

type MetaDropSubscriptionReq struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Rp       string `protobuf:"bytes,2,opt,name=rp" json:"rp,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropSubscriptionReq) Reset()                    { *m = MetaDropSubscriptionReq{} }
func (m *MetaDropSubscriptionReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDropSubscriptionReq) ProtoMessage()               {}
func (*MetaDropSubscriptionReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *MetaDropSubscriptionReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDropSubscriptionReq) GetRp() string {
	if m != nil {
		return m.Rp
	}
	return ""
}

func (m *MetaDropSubscriptionReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// user cmd
type MetaUserReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaUserReq) Reset()                    { *m = MetaUserReq{} }
func (m *MetaUserReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaUserReq) ProtoMessage()               {}
func (*MetaUserReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *MetaUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaCreateUserReq struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Admin    bool   `protobuf:"varint,3,opt,name=admin" json:"admin,omitempty"`
}

func (m *MetaCreateUserReq) Reset()                    { *m = MetaCreateUserReq{} }
func (m *MetaCreateUserReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaCreateUserReq) ProtoMessage()               {}
func (*MetaCreateUserReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *MetaCreateUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaCreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MetaCreateUserReq) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type MetaDropUserReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MetaDropUserReq) Reset()                    { *m = MetaDropUserReq{} }
func (m *MetaDropUserReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDropUserReq) ProtoMessage()               {}
func (*MetaDropUserReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *MetaDropUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaUpdateUserReq struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *MetaUpdateUserReq) Reset()                    { *m = MetaUpdateUserReq{} }
func (m *MetaUpdateUserReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaUpdateUserReq) ProtoMessage()               {}
func (*MetaUpdateUserReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *MetaUpdateUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaUpdateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// user privilege
type MetaSetAdminPrivilegeReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Admin    bool   `protobuf:"varint,2,opt,name=admin" json:"admin,omitempty"`
}

func (m *MetaSetAdminPrivilegeReq) Reset()                    { *m = MetaSetAdminPrivilegeReq{} }
func (m *MetaSetAdminPrivilegeReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaSetAdminPrivilegeReq) ProtoMessage()               {}
func (*MetaSetAdminPrivilegeReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *MetaSetAdminPrivilegeReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaSetAdminPrivilegeReq) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type MetaSetPrivilegeReq struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Database  string `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
	Privilege int64  `protobuf:"varint,3,opt,name=privilege" json:"privilege,omitempty"`
}

func (m *MetaSetPrivilegeReq) Reset()                    { *m = MetaSetPrivilegeReq{} }
func (m *MetaSetPrivilegeReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaSetPrivilegeReq) ProtoMessage()               {}
func (*MetaSetPrivilegeReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

func (m *MetaSetPrivilegeReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaSetPrivilegeReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaSetPrivilegeReq) GetPrivilege() int64 {
	if m != nil {
		return m.Privilege
	}
	return 0
}

type MetaUserPrivilegesReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *MetaUserPrivilegesReq) Reset()                    { *m = MetaUserPrivilegesReq{} }
func (m *MetaUserPrivilegesReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaUserPrivilegesReq) ProtoMessage()               {}
func (*MetaUserPrivilegesReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{21} }

func (m *MetaUserPrivilegesReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type MetaUserPrivilegeReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Database string `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
}

func (m *MetaUserPrivilegeReq) Reset()                    { *m = MetaUserPrivilegeReq{} }
func (m *MetaUserPrivilegeReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaUserPrivilegeReq) ProtoMessage()               {}
func (*MetaUserPrivilegeReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{22} }

func (m *MetaUserPrivilegeReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaUserPrivilegeReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type MetaAuthenticateReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *MetaAuthenticateReq) Reset()                    { *m = MetaAuthenticateReq{} }
func (m *MetaAuthenticateReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaAuthenticateReq) ProtoMessage()               {}
func (*MetaAuthenticateReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{23} }

func (m *MetaAuthenticateReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MetaAuthenticateReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// shard
type MetaShardGroupsByTimeRangeReq struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Policy   string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	Tmin     int64  `protobuf:"varint,3,opt,name=tmin" json:"tmin,omitempty"`
	Tmax     int64  `protobuf:"varint,4,opt,name=tmax" json:"tmax,omitempty"`
}

func (m *MetaShardGroupsByTimeRangeReq) Reset()                    { *m = MetaShardGroupsByTimeRangeReq{} }
func (m *MetaShardGroupsByTimeRangeReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaShardGroupsByTimeRangeReq) ProtoMessage()               {}
func (*MetaShardGroupsByTimeRangeReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{24} }

func (m *MetaShardGroupsByTimeRangeReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaShardGroupsByTimeRangeReq) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *MetaShardGroupsByTimeRangeReq) GetTmin() int64 {
	if m != nil {
		return m.Tmin
	}
	return 0
}

func (m *MetaShardGroupsByTimeRangeReq) GetTmax() int64 {
	if m != nil {
		return m.Tmax
	}
	return 0
}

type MetaDropShardReq struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *MetaDropShardReq) Reset()                    { *m = MetaDropShardReq{} }
func (m *MetaDropShardReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDropShardReq) ProtoMessage()               {}
func (*MetaDropShardReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{25} }

func (m *MetaDropShardReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MetaCreateShardGroupReq struct {
	Database  string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Policy    string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *MetaCreateShardGroupReq) Reset()                    { *m = MetaCreateShardGroupReq{} }
func (m *MetaCreateShardGroupReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaCreateShardGroupReq) ProtoMessage()               {}
func (*MetaCreateShardGroupReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{26} }

func (m *MetaCreateShardGroupReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaCreateShardGroupReq) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *MetaCreateShardGroupReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type MetaDeleteShardGroupReq struct {
	Database string `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Policy   string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	Id       uint64 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
}

func (m *MetaDeleteShardGroupReq) Reset()                    { *m = MetaDeleteShardGroupReq{} }
func (m *MetaDeleteShardGroupReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaDeleteShardGroupReq) ProtoMessage()               {}
func (*MetaDeleteShardGroupReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{27} }

func (m *MetaDeleteShardGroupReq) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *MetaDeleteShardGroupReq) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *MetaDeleteShardGroupReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MetaPrecreateShardGroupsReq struct {
	From int64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   int64 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
}

func (m *MetaPrecreateShardGroupsReq) Reset()                    { *m = MetaPrecreateShardGroupsReq{} }
func (m *MetaPrecreateShardGroupsReq) String() string            { return proto1.CompactTextString(m) }
func (*MetaPrecreateShardGroupsReq) ProtoMessage()               {}
func (*MetaPrecreateShardGroupsReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{28} }

func (m *MetaPrecreateShardGroupsReq) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *MetaPrecreateShardGroupsReq) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func init() {
	proto1.RegisterType((*MetaRetentionPolicySpec)(nil), "proto.MetaRetentionPolicySpec")
	proto1.RegisterType((*MetaRetentionPolicyUpdate)(nil), "proto.MetaRetentionPolicyUpdate")
	proto1.RegisterType((*MetaAcquireLeaseReq)(nil), "proto.MetaAcquireLeaseReq")
	proto1.RegisterType((*MetaCreateContinuousQueryReq)(nil), "proto.MetaCreateContinuousQueryReq")
	proto1.RegisterType((*MetaDropContinuousQueryReq)(nil), "proto.MetaDropContinuousQueryReq")
	proto1.RegisterType((*MetaDatabaseReq)(nil), "proto.MetaDatabaseReq")
	proto1.RegisterType((*MetaCreateDatabaseReq)(nil), "proto.MetaCreateDatabaseReq")
	proto1.RegisterType((*MetaCreateDatabaseWithRetentionPolicyReq)(nil), "proto.MetaCreateDatabaseWithRetentionPolicyReq")
	proto1.RegisterType((*MetaDropDatabaseReq)(nil), "proto.MetaDropDatabaseReq")
	proto1.RegisterType((*MetaCreateRetentionPolicyReq)(nil), "proto.MetaCreateRetentionPolicyReq")
	proto1.RegisterType((*MetaRetentionPolicyReq)(nil), "proto.MetaRetentionPolicyReq")
	proto1.RegisterType((*MetaDropRetentionPolicyReq)(nil), "proto.MetaDropRetentionPolicyReq")
	proto1.RegisterType((*MetaUpdateRetentionPolicyReq)(nil), "proto.MetaUpdateRetentionPolicyReq")
	proto1.RegisterType((*MetaCreateSubscriptionReq)(nil), "proto.MetaCreateSubscriptionReq")
	proto1.RegisterType((*MetaDropSubscriptionReq)(nil), "proto.MetaDropSubscriptionReq")
	proto1.RegisterType((*MetaUserReq)(nil), "proto.MetaUserReq")
	proto1.RegisterType((*MetaCreateUserReq)(nil), "proto.MetaCreateUserReq")
	proto1.RegisterType((*MetaDropUserReq)(nil), "proto.MetaDropUserReq")
	proto1.RegisterType((*MetaUpdateUserReq)(nil), "proto.MetaUpdateUserReq")
	proto1.RegisterType((*MetaSetAdminPrivilegeReq)(nil), "proto.MetaSetAdminPrivilegeReq")
	proto1.RegisterType((*MetaSetPrivilegeReq)(nil), "proto.MetaSetPrivilegeReq")
	proto1.RegisterType((*MetaUserPrivilegesReq)(nil), "proto.MetaUserPrivilegesReq")
	proto1.RegisterType((*MetaUserPrivilegeReq)(nil), "proto.MetaUserPrivilegeReq")
	proto1.RegisterType((*MetaAuthenticateReq)(nil), "proto.MetaAuthenticateReq")
	proto1.RegisterType((*MetaShardGroupsByTimeRangeReq)(nil), "proto.MetaShardGroupsByTimeRangeReq")
	proto1.RegisterType((*MetaDropShardReq)(nil), "proto.MetaDropShardReq")
	proto1.RegisterType((*MetaCreateShardGroupReq)(nil), "proto.MetaCreateShardGroupReq")
	proto1.RegisterType((*MetaDeleteShardGroupReq)(nil), "proto.MetaDeleteShardGroupReq")
	proto1.RegisterType((*MetaPrecreateShardGroupsReq)(nil), "proto.MetaPrecreateShardGroupsReq")
}

func init() { proto1.RegisterFile("meta.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xe1, 0x4e, 0x13, 0x4f,
	0x10, 0x4f, 0xef, 0x0a, 0xa1, 0x53, 0xc2, 0xff, 0xef, 0x09, 0x58, 0x11, 0x4d, 0xdd, 0xc4, 0xa4,
	0xc4, 0x84, 0x18, 0x30, 0xc6, 0xaf, 0x48, 0x13, 0x35, 0x01, 0xc4, 0xad, 0xc6, 0xf0, 0xc1, 0x0f,
	0xcb, 0xdd, 0x00, 0x1b, 0x7a, 0xb7, 0xc7, 0xee, 0x9e, 0x4a, 0x7c, 0x09, 0x13, 0xdf, 0xc2, 0xb7,
	0xf0, 0x8d, 0x7c, 0x04, 0xb3, 0x7b, 0xdb, 0xeb, 0x59, 0x7a, 0xad, 0x29, 0xc4, 0x4f, 0xec, 0x6e,
	0x67, 0x7e, 0xf3, 0x9b, 0xf9, 0xcd, 0xcc, 0x01, 0x10, 0xa3, 0x66, 0x9b, 0xa9, 0x14, 0x5a, 0x04,
	0x73, 0xf6, 0xcf, 0xda, 0x62, 0x28, 0xe2, 0x58, 0x24, 0xf9, 0x23, 0xf9, 0x59, 0x83, 0x3b, 0xfb,
	0xa8, 0x19, 0x45, 0x8d, 0x89, 0xe6, 0x22, 0x39, 0x14, 0x7d, 0x1e, 0x5e, 0xf6, 0x52, 0x0c, 0x83,
	0x00, 0xea, 0x09, 0x8b, 0xb1, 0x55, 0x6b, 0xd7, 0x3a, 0x0d, 0x6a, 0xcf, 0xc1, 0x13, 0x58, 0x90,
	0x98, 0xf6, 0x79, 0xc8, 0x0e, 0x5a, 0x5e, 0xbb, 0xd6, 0x69, 0x6e, 0x2d, 0xe7, 0x48, 0x9b, 0x6f,
	0x52, 0xe3, 0xce, 0xfa, 0xaf, 0x13, 0xfd, 0xec, 0x29, 0x2d, 0xac, 0x8c, 0x47, 0x94, 0x49, 0x66,
	0x7e, 0x6c, 0xf9, 0x93, 0x3c, 0x06, 0x56, 0xc1, 0x26, 0x04, 0xbd, 0x33, 0x26, 0xa3, 0x97, 0x52,
	0x64, 0x69, 0x77, 0xe0, 0x5b, 0x6f, 0xd7, 0x3a, 0x3e, 0x1d, 0xf3, 0x0b, 0xf9, 0x55, 0x83, 0xbb,
	0x63, 0x72, 0x78, 0x9f, 0x46, 0x4c, 0x63, 0xb0, 0x51, 0xca, 0xa2, 0xb9, 0xb5, 0x32, 0x12, 0xbb,
	0xa7, 0x25, 0x4f, 0x4e, 0xff, 0x61, 0x72, 0xdd, 0xca, 0xe4, 0xaa, 0x7c, 0xc7, 0xa5, 0xbc, 0x01,
	0xb7, 0x4d, 0xc6, 0x3b, 0xe1, 0x45, 0xc6, 0x25, 0xee, 0x21, 0x53, 0x48, 0xf1, 0x62, 0x9c, 0x62,
	0x24, 0x82, 0x75, 0x63, 0xba, 0x2b, 0x91, 0x69, 0xdc, 0x15, 0x89, 0xe6, 0x49, 0x26, 0x32, 0xf5,
	0x36, 0x43, 0x79, 0x69, 0x7c, 0xd6, 0x60, 0x21, 0x62, 0x9a, 0x1d, 0x33, 0x35, 0xf0, 0x2b, 0xee,
	0x05, 0x9e, 0x57, 0xea, 0x80, 0x65, 0x98, 0xbb, 0x30, 0xbe, 0x36, 0xdf, 0x06, 0xcd, 0x2f, 0x64,
	0x0f, 0xd6, 0x4c, 0x94, 0xae, 0x14, 0xe9, 0xf5, 0x63, 0x90, 0x47, 0xf0, 0x9f, 0x45, 0x73, 0x36,
	0x55, 0xa9, 0x3d, 0x86, 0x95, 0x61, 0x6a, 0xd3, 0x8c, 0x25, 0x74, 0xae, 0x1a, 0x7f, 0xe0, 0xfa,
	0x6c, 0xa4, 0x6d, 0x2a, 0xfc, 0x83, 0x2d, 0xa8, 0xab, 0x14, 0x43, 0xd7, 0x18, 0x0f, 0x9c, 0x54,
	0x15, 0xb3, 0x43, 0xad, 0xed, 0x40, 0x26, 0x53, 0x95, 0x69, 0xf4, 0xbe, 0xd5, 0xca, 0x3a, 0x8d,
	0xe1, 0x34, 0xa9, 0x86, 0x33, 0x70, 0x0b, 0xda, 0xd0, 0x8c, 0xd9, 0x39, 0x76, 0xf1, 0x84, 0x65,
	0x7d, 0x6d, 0xd5, 0x5c, 0xa0, 0xe5, 0x27, 0xf2, 0x0a, 0x56, 0xc7, 0x40, 0xcc, 0xa2, 0x67, 0xa9,
	0x3b, 0x6e, 0x00, 0xed, 0x87, 0x2b, 0x55, 0x3e, 0xe0, 0xd7, 0x07, 0x0c, 0x9e, 0xc3, 0x7c, 0x66,
	0xb1, 0xdc, 0x0c, 0xb7, 0xab, 0x0b, 0xe8, 0x62, 0x3a, 0xfb, 0xd1, 0x22, 0xd6, 0xaf, 0x16, 0xf1,
	0xbb, 0x5b, 0x4e, 0xb9, 0xae, 0xbd, 0xec, 0x58, 0x85, 0x92, 0xdb, 0xf9, 0x9e, 0xc6, 0x74, 0x09,
	0x3c, 0x99, 0x3a, 0x9e, 0x9e, 0x4c, 0x0b, 0xe6, 0x7e, 0x89, 0x79, 0x00, 0xf5, 0x58, 0x44, 0x68,
	0x03, 0x37, 0xa8, 0x3d, 0x07, 0x04, 0x16, 0x23, 0x54, 0x9a, 0x27, 0x76, 0x55, 0xa8, 0xd6, 0x5c,
	0xdb, 0xef, 0x34, 0xe8, 0x1f, 0x6f, 0xe4, 0x28, 0xdf, 0xfa, 0x46, 0x90, 0x1b, 0xa6, 0x44, 0x1e,
	0x42, 0xd3, 0x8a, 0xa3, 0x50, 0x56, 0xf5, 0xfa, 0x11, 0xdc, 0x1a, 0x96, 0x64, 0x82, 0xa1, 0xe1,
	0x92, 0x32, 0xa5, 0x3e, 0x0b, 0x19, 0xb9, 0xa8, 0xc5, 0xdd, 0xec, 0x21, 0x16, 0xc5, 0x3c, 0x71,
	0x9d, 0x9b, 0x5f, 0x8a, 0xcd, 0x21, 0x45, 0x3a, 0x89, 0xc1, 0x6e, 0xce, 0x20, 0x57, 0x73, 0x46,
	0x06, 0x64, 0x0f, 0x5a, 0x06, 0xa4, 0x87, 0x7a, 0xc7, 0xc4, 0x3e, 0x94, 0xfc, 0x13, 0xef, 0xe3,
	0x29, 0xba, 0x2a, 0x66, 0x0a, 0x65, 0x09, 0xaf, 0xb8, 0x0f, 0x99, 0x7b, 0x65, 0xe6, 0xe7, 0xf9,
	0xae, 0xe8, 0xa1, 0xfe, 0x6b, 0xa0, 0xb2, 0x54, 0xde, 0x88, 0x54, 0xeb, 0xd0, 0x48, 0x07, 0x38,
	0xb6, 0x44, 0x3e, 0x1d, 0x3e, 0x90, 0xed, 0x7c, 0x73, 0x9a, 0xcc, 0x8b, 0x68, 0x6a, 0x4a, 0x38,
	0x72, 0x00, 0xcb, 0x57, 0x9c, 0xae, 0x41, 0x91, 0xec, 0xbb, 0x8f, 0x58, 0xa6, 0xcf, 0xcc, 0x88,
	0x85, 0x76, 0x98, 0xa7, 0xc2, 0x55, 0xca, 0xf1, 0x15, 0xee, 0xdb, 0x02, 0x16, 0x5f, 0x4b, 0xf5,
	0xe2, 0xf2, 0x1d, 0x8f, 0x91, 0xb2, 0xa4, 0xe0, 0x59, 0xd9, 0xd9, 0xab, 0x30, 0x9f, 0xda, 0x01,
	0x77, 0xb0, 0xee, 0x66, 0x7a, 0x42, 0x0f, 0x9a, 0xcc, 0xa7, 0xf6, 0x9c, 0xbf, 0xb1, 0x2f, 0xee,
	0x3f, 0x12, 0x7b, 0x26, 0x04, 0xfe, 0x2f, 0x06, 0xca, 0x10, 0x30, 0xf1, 0x96, 0xc0, 0xe3, 0x91,
	0x8d, 0x54, 0xa7, 0x1e, 0x8f, 0xc8, 0x79, 0x3e, 0x74, 0x6e, 0x13, 0x14, 0x34, 0x67, 0xa5, 0xb6,
	0x0e, 0x0d, 0xcd, 0x63, 0x54, 0x9a, 0xc5, 0xe9, 0x40, 0xe1, 0xe2, 0x81, 0x7c, 0x74, 0x13, 0x8e,
	0x7d, 0xbc, 0x89, 0x60, 0x79, 0x2e, 0x7e, 0x91, 0xcb, 0x0e, 0xdc, 0x33, 0xf0, 0x87, 0x12, 0xc3,
	0x91, 0x74, 0x94, 0x1b, 0xa5, 0x13, 0x29, 0x62, 0x0b, 0xef, 0x53, 0x7b, 0x36, 0x10, 0x5a, 0x58,
	0x58, 0x9f, 0x7a, 0x5a, 0x1c, 0xcf, 0xdb, 0x25, 0xbb, 0xfd, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0xde, 0xf3, 0xad, 0xa4, 0x0a, 0x00, 0x00,
}
