// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster_common.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	cluster_common.proto
	common.proto
	meta_cmd.proto
	meta_data.proto
	meta_service.proto

It has these top-level messages:
	ClusterLeader
	ClusterResult
	Str
	I64
	MetaCmdCreateMetaNode
	MetaData
	MetaLease
	MetaNodeInfo
	MetaDatabaseInfo
	MetaRetentionPolicySpec
	MetaRetentionPolicyInfo
	MetaShardGroupInfo
	MetaShardInfo
	MetaSubscriptionInfo
	MetaShardOwner
	MetaContinuousQueryInfo
	MetaUserInfo
	MetaUserPrivilege
	MetaJoinReq
	MetaJoinResp
	MetaRemoveReq
	MetaRemoveResp
	MetaApplyReq
	MetaApplyResp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResultCode int32

const (
	ResultCode_ResultCodeUnknown           ResultCode = 0
	ResultCode_ResultCodeOK                ResultCode = 1
	ResultCode_ResultCodeErrNotLeader      ResultCode = 1001
	ResultCode_ResultCodeErrLeadershipLost ResultCode = 1002
)

var ResultCode_name = map[int32]string{
	0:    "ResultCodeUnknown",
	1:    "ResultCodeOK",
	1001: "ResultCodeErrNotLeader",
	1002: "ResultCodeErrLeadershipLost",
}
var ResultCode_value = map[string]int32{
	"ResultCodeUnknown":           0,
	"ResultCodeOK":                1,
	"ResultCodeErrNotLeader":      1001,
	"ResultCodeErrLeadershipLost": 1002,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}
func (ResultCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ClusterLeader struct {
	Available bool   `protobuf:"varint,1,opt,name=available" json:"available,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *ClusterLeader) Reset()                    { *m = ClusterLeader{} }
func (m *ClusterLeader) String() string            { return proto.CompactTextString(m) }
func (*ClusterLeader) ProtoMessage()               {}
func (*ClusterLeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClusterLeader) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *ClusterLeader) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ClusterResult struct {
	Code   ResultCode     `protobuf:"varint,1,opt,name=code,enum=pb.ResultCode" json:"code,omitempty"`
	Msg    string         `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Leader *ClusterLeader `protobuf:"bytes,3,opt,name=leader" json:"leader,omitempty"`
}

func (m *ClusterResult) Reset()                    { *m = ClusterResult{} }
func (m *ClusterResult) String() string            { return proto.CompactTextString(m) }
func (*ClusterResult) ProtoMessage()               {}
func (*ClusterResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClusterResult) GetCode() ResultCode {
	if m != nil {
		return m.Code
	}
	return ResultCode_ResultCodeUnknown
}

func (m *ClusterResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ClusterResult) GetLeader() *ClusterLeader {
	if m != nil {
		return m.Leader
	}
	return nil
}

func init() {
	proto.RegisterType((*ClusterLeader)(nil), "pb.ClusterLeader")
	proto.RegisterType((*ClusterResult)(nil), "pb.ClusterResult")
	proto.RegisterEnum("pb.ResultCode", ResultCode_name, ResultCode_value)
}

func init() { proto.RegisterFile("cluster_common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xcd, 0x26, 0xab, 0xfb, 0xd4, 0x91, 0x7d, 0xa8, 0x14, 0xe6, 0xa1, 0xf4, 0x54, 0x3d,
	0xf4, 0x30, 0x7f, 0xc2, 0x10, 0x0f, 0x0e, 0x85, 0x80, 0x67, 0x49, 0x9b, 0xa0, 0xc3, 0xb4, 0x5f,
	0x48, 0x32, 0xfd, 0xcd, 0xfa, 0x2b, 0x64, 0xcd, 0x34, 0xec, 0x96, 0xf7, 0x7d, 0x92, 0x87, 0x97,
	0xc0, 0x45, 0x6b, 0xb6, 0x3e, 0x68, 0xf7, 0xda, 0x52, 0xd7, 0x51, 0x5f, 0x5b, 0x47, 0x81, 0x70,
	0x64, 0x9b, 0xf2, 0x01, 0xce, 0x57, 0x91, 0xad, 0xb5, 0x54, 0xda, 0xe1, 0x35, 0x4c, 0xe5, 0xa7,
	0xdc, 0x18, 0xd9, 0x18, 0x9d, 0xb3, 0x82, 0x55, 0x27, 0x22, 0x15, 0x98, 0x43, 0x26, 0x95, 0x72,
	0xda, 0xfb, 0x7c, 0x54, 0xb0, 0x6a, 0x2a, 0xfe, 0x62, 0x69, 0xff, 0x45, 0x42, 0xfb, 0xad, 0x09,
	0x58, 0xc2, 0x71, 0x4b, 0x2a, 0x3a, 0x66, 0xcb, 0x59, 0x6d, 0x9b, 0x3a, 0x92, 0x15, 0x29, 0x2d,
	0x06, 0x86, 0x1c, 0xc6, 0x9d, 0x7f, 0xdb, 0xab, 0x76, 0x47, 0xbc, 0x81, 0x89, 0x19, 0x86, 0xe4,
	0xe3, 0x82, 0x55, 0xa7, 0xcb, 0xf9, 0xee, 0xdd, 0xc1, 0x42, 0xb1, 0xbf, 0x70, 0x1b, 0x00, 0x92,
	0x10, 0x2f, 0x61, 0x9e, 0xd2, 0x4b, 0xff, 0xd1, 0xd3, 0x57, 0xcf, 0x8f, 0x90, 0xc3, 0x59, 0xaa,
	0x9f, 0x1f, 0x39, 0xc3, 0x05, 0x5c, 0xa5, 0xe6, 0xde, 0xb9, 0x27, 0x0a, 0x51, 0xcc, 0xbf, 0x33,
	0x2c, 0x60, 0x71, 0x00, 0x23, 0xf1, 0xef, 0x1b, 0xbb, 0x26, 0x1f, 0xf8, 0x4f, 0xd6, 0x4c, 0x86,
	0xbf, 0xbb, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x54, 0x28, 0x08, 0xa6, 0x53, 0x01, 0x00, 0x00,
}
