// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Str struct {
	Val string `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
}

func (m *Str) Reset()                    { *m = Str{} }
func (m *Str) String() string            { return proto.CompactTextString(m) }
func (*Str) ProtoMessage()               {}
func (*Str) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Str) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type I64 struct {
	Val int64 `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
}

func (m *I64) Reset()                    { *m = I64{} }
func (m *I64) String() string            { return proto.CompactTextString(m) }
func (*I64) ProtoMessage()               {}
func (*I64) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *I64) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterType((*Str)(nil), "pb.Str")
	proto.RegisterType((*I64)(nil), "pb.I64")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x12, 0xe7, 0x62,
	0x0e, 0x2e, 0x29, 0x12, 0x12, 0xe0, 0x62, 0x2e, 0x4b, 0xcc, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0x31, 0x41, 0x12, 0x9e, 0x66, 0x26, 0x30, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x66, 0xb0,
	0x44, 0x12, 0x1b, 0x58, 0xb3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x01, 0x9a, 0x0c, 0x2a, 0x4c,
	0x00, 0x00, 0x00,
}
