// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	cmd.proto

It has these top-level messages:
	CreateUserCmd
	UpdateUserCmd
	DropUserCmd
	UserPrivilegeCmd
	UserPrivilegesCmd
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserCmd struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Admin    bool   `protobuf:"varint,3,opt,name=admin" json:"admin,omitempty"`
}

func (m *CreateUserCmd) Reset()                    { *m = CreateUserCmd{} }
func (m *CreateUserCmd) String() string            { return proto.CompactTextString(m) }
func (*CreateUserCmd) ProtoMessage()               {}
func (*CreateUserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserCmd) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserCmd) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type UpdateUserCmd struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UpdateUserCmd) Reset()                    { *m = UpdateUserCmd{} }
func (m *UpdateUserCmd) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserCmd) ProtoMessage()               {}
func (*UpdateUserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateUserCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserCmd) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type DropUserCmd struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DropUserCmd) Reset()                    { *m = DropUserCmd{} }
func (m *DropUserCmd) String() string            { return proto.CompactTextString(m) }
func (*DropUserCmd) ProtoMessage()               {}
func (*DropUserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DropUserCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserPrivilegeCmd struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Database string `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
}

func (m *UserPrivilegeCmd) Reset()                    { *m = UserPrivilegeCmd{} }
func (m *UserPrivilegeCmd) String() string            { return proto.CompactTextString(m) }
func (*UserPrivilegeCmd) ProtoMessage()               {}
func (*UserPrivilegeCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserPrivilegeCmd) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserPrivilegeCmd) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type UserPrivilegesCmd struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *UserPrivilegesCmd) Reset()                    { *m = UserPrivilegesCmd{} }
func (m *UserPrivilegesCmd) String() string            { return proto.CompactTextString(m) }
func (*UserPrivilegesCmd) ProtoMessage()               {}
func (*UserPrivilegesCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserPrivilegesCmd) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserCmd)(nil), "internal.CreateUserCmd")
	proto.RegisterType((*UpdateUserCmd)(nil), "internal.UpdateUserCmd")
	proto.RegisterType((*DropUserCmd)(nil), "internal.DropUserCmd")
	proto.RegisterType((*UserPrivilegeCmd)(nil), "internal.UserPrivilegeCmd")
	proto.RegisterType((*UserPrivilegesCmd)(nil), "internal.UserPrivilegesCmd")
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xce, 0x4d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x51,
	0x0a, 0xe5, 0xe2, 0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x2d, 0x4e, 0x2d, 0x72, 0xce, 0x4d,
	0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x85, 0xa4, 0xb8, 0x38, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0xc0,
	0xe2, 0x70, 0xbe, 0x90, 0x08, 0x17, 0x6b, 0x62, 0x4a, 0x6e, 0x66, 0x9e, 0x04, 0xb3, 0x02, 0xa3,
	0x06, 0x47, 0x10, 0x84, 0xa3, 0x64, 0xcf, 0xc5, 0x1b, 0x5a, 0x90, 0x42, 0xbe, 0xb1, 0x4a, 0x8a,
	0x5c, 0xdc, 0x2e, 0x45, 0xf9, 0x05, 0x78, 0xb4, 0x2b, 0x79, 0x71, 0x09, 0x80, 0xa4, 0x03, 0x8a,
	0x32, 0xcb, 0x32, 0x73, 0x52, 0xd3, 0x53, 0x41, 0xea, 0xa4, 0xb8, 0x38, 0x4a, 0x8b, 0x41, 0x3e,
	0x83, 0xab, 0x85, 0xf3, 0x41, 0x72, 0x29, 0x89, 0x25, 0x89, 0x49, 0x89, 0xc5, 0xa9, 0x30, 0xeb,
	0x60, 0x7c, 0x25, 0x7d, 0x2e, 0x41, 0x14, 0xb3, 0x8a, 0x09, 0x18, 0x96, 0xc4, 0x06, 0x0e, 0x48,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x1b, 0x53, 0xf3, 0x55, 0x01, 0x00, 0x00,
}
